### ISSUE TITLE
emitWithBinary: Converting object to an encodable object failed

### ISSUE THREAD

**Issue by cTatu** [rikulo/socket.io-client-dart#114]
I wanted to send an image from my assets folder as so:
```dart
ByteData img = await rootBundle.load('assets/testapp.jpg');
socket.emitWithBinary('image', img.buffer);
// I tried this also:
socket.emitWithBinary('image', img);
```
But it keeps throwing this error:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: Converting object to an encodable object failed: Instance of '_ByteBuffer'
E/flutter (10899): #0      _JsonStringifier.writeObject (dart:convert/json.dart:687:7)
E/flutter (10899): #1      _JsonStringifier.writeList (dart:convert/json.dart:738:9)
E/flutter (10899): #2      _JsonStringifier.writeJsonValue (dart:convert/json.dart:717:7)
E/flutter (10899): #3      _JsonStringifier.writeObject (dart:convert/json.dart:678:9)
E/flutter (10899): #4      _JsonStringStringifier.printOn (dart:convert/json.dart:876:17)
E/flutter (10899): #5      _JsonStringStringifier.stringify (dart:convert/json.dart:861:5)
E/flutter (10899): #6      JsonEncoder.convert (dart:convert/json.dart:261:30)
E/flutter (10899): #7      JsonCodec.encode (dart:convert/json.dart:171:45)
E/flutter (10899): #8      Encoder.encodeAsString (package:socket_io_common/src/parser/parser.dart:97:19)
E/flutter (10899): #9      Encoder.encodeAsBinary.<anonymous closure> (package:socket_io_common/src/parser/parser.dart:117:18)
E/flutter (10899): #10     Encoder.encodeAsBinary (package:socket_io_common/src/parser/parser.dart:125:18)
E/flutter (10899): #11     Encoder.encode (package:socket_io_common/src/parser/parser.dart:60:7)
E/flutter (10899): #12     Manager.packet (package:socket_io_client/src/manager.dart:380:15)
E/flutter (10899): #13     Socket.packet (package:socket_io_client/src/socket.dart:184:8)
E/flutter (10899): #14     Socket.emitWithAck (package:socket_io_client/src/socket.dart:169:14)
E/flutter (10899): #15     Socket.emitWithBinary (package:socket_io_client/src/socket.dart:133:5)
E/flutter (10899): #16     _MyHomePageState.setupSocket.<anonymous closure> (package:myapp/main.dart:58:14)
```

**Comment by CongBaDo** [comment]
How can you send the image file?
