### ISSUE TITLE
Why am I getting this 'TypeError: Cannot read property 'name' of null'?

### ISSUE THREAD

**Issue by mhbdev** [rikulo/socket.io-client-dart#154]
This is not telling complete story about what's happening behind :( does anybody know what's the problem producing this warning/error!

```
TypeError: Cannot read property 'name' of null
    at Object.dcall (http://localhost:64824/dart_sdk.js:4563:69)
    at http://localhost:64824/packages/socket_io_common/src/util/event_emitter.dart.lib.js:37:14
    at Array.[dartx.forEach] (http://localhost:64824/dart_sdk.js:14949:11)
    at socket$0.Socket.new.emit (http://localhost:64824/packages/socket_io_common/src/util/event_emitter.dart.lib.js:36:39)
    at socket$0.Socket.new.emitWithAck (http://localhost:64824/packages/socket_io_client/src/manager.dart.lib.js:777:15)
```

**Comment by jumperchen** [comment]
which version and env. are you using?

**Comment by mhbdev** [comment]
This has been solved on the last version of the library. Or maybe I was using it wrong. But now everything is ok. Thanks.
