### ISSUE TITLE
LateInitializationError: Field 'engine' has not been initialized.

### ISSUE THREAD

**Issue by kevan-ivadolabs** [rikulo/socket.io-client-dart#211]
Hello everyone,

It seems that v1.0.1 of the library has a `LateInitializationError` in certain situations. I have attached the full stack trace at the bottom, but essentially, I ran into this error after running my app with null safety on in Chrome. In my app, I have a `SocketStream` class that holds a Socket property built as follow:

```
class SocketStream {

  final StreamController<InboundEvent> _socketStreamController = StreamController<InboundEvent>();
  // Note that the socket is not allowed to connect automatically
  final Socket _socket = io(
      EnvConfig.SERVER_URL,
      OptionBuilder()
          .disableAutoConnect()
          .setTransports(<String>['websocket'])
          .setExtraHeaders(<String, String>{'playerId': ''})
          .setQuery(<dynamic, dynamic>{'playerId': ''})
          .build());
}
```

Based on the stack trace, the issue seems to be in the `Manager` class which only initializes the engine upon a call to the connect method, which in my case is likely not called immediately as I disabled the AutoConnect feature:

~socket_io_client/src/manager.dart
```
class Manager extends EventEmitter {
late engine_socket.Socket engine;
// ... more properties...

Manager connect({callback, Map? opts}) {
    _logger.fine('readyState $readyState');
    if (readyState.contains('open')) return this;

    _logger.fine('opening $uri');
    // Our issue:
    engine = engine_socket.Socket(uri, options);
    // more logic....
    // even more logic...
    return this;
  }
}
```

Should my implementation be tweaked or do we have options to instantiate the engine property in the Manager class. I am not a professional developer, so please do not hesitate to let me know if I got any of this wrong, thanks in advance! :)

Full stack trace:
`Error: LateInitializationError: Field 'engine' has not been initialized.
    at Object.throw_ [as throw] (http://localhost:55381/dart_sdk.js:5041:11)
    at manager.Manager.new.get engine [as engine] (http://localhost:55381/packages/socket_io_client/src/manager.dart.lib.js:200:37)
    at manager.Manager.new.disconnect (http://localhost:55381/packages/socket_io_client/src/manager.dart.lib.js:404:12)
    at manager.Manager.new.close (http://localhost:55381/packages/socket_io_client/src/manager.dart.lib.js:393:19)
    at manager.Manager.new.destroy (http://localhost:55381/packages/socket_io_client/src/manager.dart.lib.js:351:12)
    at socket$0.Socket.new.destroy (http://localhost:55381/packages/socket_io_client/src/manager.dart.lib.js:947:15)
    at socket$0.Socket.new.disconnect (http://localhost:55381/packages/socket_io_client/src/manager.dart.lib.js:957:12)
    at socket$0.Socket.new.dispose (http://localhost:55381/packages/socket_io_client/src/manager.dart.lib.js:964:12)
    at socket_stream.SocketStream.new.disconnectSocket (http://localhost:55381/packages/chessfantasy/services/socket/socket_stream.dart.lib.js:125:21)
    at socket_controller.SocketController.new.disconnectSocketConnection
    (http://localhost:55381/packages/chessfantasy/controllers/socket_controller.dart.lib.js:50:27)
    at http://localhost:55381/packages/chessfantasy/ui/screens/signup_view.dart.lib.js:4308:93
    at _RootZone.runUnaryGuarded (http://localhost:55381/dart_sdk.js:37211:11)
    at _SinkTransformerStreamSubscription.new.[_sendData] (http://localhost:55381/dart_sdk.js:31145:22)
    at _SinkTransformerStreamSubscription.new.[_add] (http://localhost:55381/dart_sdk.js:31094:26)
    at _SinkTransformerStreamSubscription.new.[_add] (http://localhost:55381/dart_sdk.js:35748:20)
    at _EventSinkWrapper.new.add (http://localhost:55381/dart_sdk.js:35697:27)
    at auth_controller.AuthController.new.<anonymous> (http://localhost:55381/packages/chessfantasy/ui/screens/signup_view.dart.lib.js:4349:20)
    at Generator.next (<anonymous>)
    at runBody (http://localhost:55381/dart_sdk.js:37422:34)
    at Object._async [as async] (http://localhost:55381/dart_sdk.js:37453:7)
    at http://localhost:55381/packages/chessfantasy/ui/screens/signup_view.dart.lib.js:4346:113
    at _HandlerEventSink.new.add (http://localhost:55381/dart_sdk.js:35947:11)
    at _SinkTransformerStreamSubscription.new.[_handleData] (http://localhost:55381/dart_sdk.js:35783:34)
    at _RootZone.runUnaryGuarded (http://localhost:55381/dart_sdk.js:37211:11)
    at _BroadcastSubscription.new.[_sendData] (http://localhost:55381/dart_sdk.js:31145:22)
    at _BroadcastSubscription.new.[_add] (http://localhost:55381/dart_sdk.js:31094:26)
    at _AsBroadcastStreamController.new.[_sendData] (http://localhost:55381/dart_sdk.js:31788:34)
    at _AsBroadcastStreamController.new.add (http://localhost:55381/dart_sdk.js:31587:24)
    at _AsBroadcastStreamController.new.add (http://localhost:55381/dart_sdk.js:31899:15)
    at _RootZone.runUnaryGuarded (http://localhost:55381/dart_sdk.js:37211:11)
    at _ForwardingStreamSubscription.new.[_sendData] (http://localhost:55381/dart_sdk.js:31145:22)
    at _ForwardingStreamSubscription.new.[_add] (http://localhost:55381/dart_sdk.js:31094:26)
    at _ForwardingStreamSubscription.new.[_add] (http://localhost:55381/dart_sdk.js:35157:20)
    at _MapStream.new.[_handleData] (http://localhost:55381/dart_sdk.js:35279:19)
    at _ForwardingStreamSubscription.new.[_handleData] (http://localhost:55381/dart_sdk.js:35183:37)
    at _RootZone.runUnaryGuarded (http://localhost:55381/dart_sdk.js:37211:11)
    at _ControllerSubscription.new.[_sendData] (http://localhost:55381/dart_sdk.js:31145:22)
    at _DelayedData.new.perform (http://localhost:55381/dart_sdk.js:34417:28)
    at _StreamImplEvents.new.handleNext (http://localhost:55381/dart_sdk.js:34521:15)
    at async._AsyncCallbackEntry.new.callback (http://localhost:55381/dart_sdk.js:34282:16)
    at Object._microtaskLoop (http://localhost:55381/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:55381/dart_sdk.js:37532:13)
    at http://localhost:55381/dart_sdk.js:33303:9`

**Comment by jumperchen** [comment]
It seems that your code is not fully initiated the Socket instance by invoking  either `connect()` or `auto-connect` feature, but it called `dispose()` to disconnect the Socket instance from the stack trace. So do you consider to change your implementation to follow the correct way to initiate the Socket instance or should I raise it as a Bug?

**Comment by kevan-ivadolabs** [comment]
hi @jumperchen , thanks for the quick reply. I think you nailed it! I had authentication logic which would call `.dispose() `on the socket upon log out even though the socket had sometimes not been connected. I added a condition to dispose only sockets with specific listeners and it worked. Thanks again.
