### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by kevin4dhd** [rikulo/socket.io-client-dart#219]
I am testing this library, and when I run I get the following error in connect_error

![image](https://user-images.githubusercontent.com/22886367/130092901-beb40134-931a-4ff9-99c3-f0a2eb8ae7cb.png)

No tengo ni idea de porque ocurre este error

**Comment by kevin4dhd** [comment]
I managed to catch the error

#0 _WebSocketImpl.connect.<anonymous closure> (dart:_http/websocket_impl.dart:1065:60) #1 _rootRunUnary (dart:async/zone.dart:1362:47) #2 _CustomZone.runUnary (dart:async/zone.dart:1265:19) <asynchronous suspension> #3 IOWebSocketTransport.doOpen (package:socket_io_client/src/engine/transport/io_websocket_transport.dart:42:12)

**Comment by jumperchen** [comment]
FYI: https://github.com/rikulo/socket.io-client-dart#usage-flutter
