### ISSUE TITLE
[package bug] Unimplemented handling of missing static target

### ISSUE THREAD

**Issue by hatemragab** [rikulo/socket.io-client-dart#295]
```
Unhandled Exception: Unimplemented handling of missing static target
E/flutter (26353): #0      EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
E/flutter (26353): #1      List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (26353): #2      EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
E/flutter (26353): #3      Function._apply (dart:core-patch/function_patch.dart:11:73)
E/flutter (26353): #4      Function.apply (dart:core-patch/function_patch.dart:34:12)
E/flutter (26353): #5      Socket.onevent (package:socket_io_client/src/socket.dart:308:18)
E/flutter (26353): #6      Socket.onpacket (package:socket_io_client/src/socket.dart:264:9)
E/flutter (26353): #7      EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
E/flutter (26353): #8      List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (26353): #9      EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
E/flutter (26353): #10     Manager.ondecoded (package:socket_io_client/src/manager.dart:253:5)
E/flutter (26353): #11     EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
E/flutter (26353): #12     List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (26353): #13     EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
E/flutter (26353): #14     Decoder.add (package:socket_io_common/src/parser/parser.dart:160:14)
E/flutter (26353): #15     Manager.ondata (package:socket_io_client/src/manager.dart:244:13)
E/flutter (26353): #16     EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
E/flutter (26353): #17     List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (26353): #18     EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
E/flutter (26353): #19     Socket.onPacket (package:socket_io_client/src/engine/socket.dart:463:11)
E/flutter (26353): #20     Socket.setTransport.<anonymous closure> (package:socket_io_client/src/engine/socket.dart:287:34)
E/flutter (26353): #21     EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
E/flutter (26353): #22     List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (26353): #23     EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
E/flutter (26353): #24     Transport.onPacket (package:socket_io_client/src/engine/transport/transport.dart:127:5)
E/flutter (26353): #25     Transport.onData (package:socket_io_client/src/engine/transport/transport.dart:121:5)
E/flutter (26353): #26     IOWebSocketTransport.addEventListeners.<anonymous closure> (package:socket_io_client/src/engine/transport/io_websocket_transport.dart:67:7)
E/flutter (26353): #27     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (26353): #28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (26353): #29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (26353): #30     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
E/flutter (26353): #31     _StreamController._add (dart:async/stream_controller.dart:648:7)
E/flutter (26353): #32     _StreamController.add (dart:async/stream_controller.dart:596:5)
E/flutter (26353): #33     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1144:21)
E/flutter (26353): #34     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (26353): #35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (26353): #36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (26353): #37     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
E/flutter (26353): #38     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
E/flutter (26353): #39     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:332:23)
E/flutter (26353): #40     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:226:46)
E/flutter (26353): #41     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
E/flutter (26353): #42     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (26353): #43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (26353): #44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (26353): #45     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
E/flutter (26353): #46     _StreamController._add (dart:async/stream_controller.dart:648:7)
E/flutter (26353): #47     _StreamController.add (dart:async/stream_controller.dart:596:5)
E/flutter (26353): #48     _Socket._onData (dart:io-patch/socket_patch.dart:2324:41)
E/flutter (26353): #49     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (26353): #50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (26353): #51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (26353): #52     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
E/flutter (26353): #53     _StreamController._add (dart:async/stream_controller.dart:648:7)
E/flutter (26353): #54     _StreamController.add (dart:async/stream_controller.dart:596:5)
E/flutter (26353): #55     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1849:33)
E/flutter (26353): #56     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1322:14)
E/flutter (26353): #57     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (26353): #58     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (26353): 
E/flutter (26353): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unimplemented handling of missing static target
E/flutter (26353): #0      EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
E/flutter (26353): #1      List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (26353): #2      EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
E/flutter (26353): #3      Function._apply (dart:core-patch/function_patch.dart:11:73)
E/flutter (26353): #4      Function.apply (dart:core-patch/function_patch.dart:34:12)
E/flutter (26353): #5      Socket.onevent (package:socket_io_client/src/socket.dart:308:18)
E/flutter (26353): #6      Socket.onpacket (package:socket_io_client/src/socket.dart:264:9)
E/flutter (26353): #7      EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
E/flutter (26353): #8      List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (26353): #9      EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
E/flutter (26353): #10     Manager.ondecoded (package:socket_io_client/src/manager.dart:253:5)
E/flutter (26353): #11     EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
E/flutter (26353): #12     List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (26353): #13     EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
E/flutter (26353): #14     Decoder.add (package:socket_io_common/src/parser/parser.dart:160:14)
E/flutter (26353): #15     Manager.ondata (package:socket_io_client/src/manager.dart:244:13)
E/flutter (26353): #16     EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
E/flutter (26353): #17     List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (26353): #18     EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
E/flutter (26353): #19     Socket.onPacket (package:socket_io_client/src/engine/socket.dart:463:11)
E/flutter (26353): #20     Socket.setTransport.<anonymous closure> (package:socket_io_client/src/engine/socket.dart:287:34)
E/flutter (26353): #21     EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
E/flutter (26353): #22     List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (26353): #23     EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
E/flutter (26353): #24     Transport.onPacket (package:socket_io_client/src/engine/transport/transport.dart:127:5)
E/flutter (26353): #25     Transport.onData (package:socket_io_client/src/engine/transport/transport.dart:121:5)
E/flutter (26353): #26     IOWebSocketTransport.addEventListeners.<anonymous closure> (package:socket_io_client/src/engine/transport/io_websocket_transport.dart:67:7)
E/flutter (26353): #27     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (26353): #28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (26353): #29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (26353): #30     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
E/flutter (26353): #31     _StreamController._add (dart:async/stream_controller.dart:648:7)
E/flutter (26353): #32     _StreamController.add (dart:async/stream_controller.dart:596:5)
E/flutter (26353): #33     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1144:21)
E/flutter (26353): #34     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (26353): #35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (26353): #36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (26353): #37     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
E/flutter (26353): #38     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
E/flutter (26353): #39     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:332:23)
E/flutter (26353): #40     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:226:46)
E/flutter (26353): #41     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
E/flutter (26353): #42     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (26353): #43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (26353): #44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (26353): #45     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
E/flutter (26353): #46     _StreamController._add (dart:async/stream_controller.dart:648:7)
E/flutter (26353): #47     _StreamController.add (dart:async/stream_controller.dart:596:5)
E/flutter (26353): #48     _Socket._onData (dart:io-patch/socket_patch.dart:2324:41)
E/flutter (26353): #49     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (26353): #50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (26353): #51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (26353): #52     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
E/flutter (26353): #53     _StreamController._add (dart:async/stream_controller.dart:648:7)
E/flutter (26353): #54     _StreamController.add (dart:async/stream_controller.dart:596:5)
E/flutter (26353): #55     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1849:33)
E/flutter (26353): #56     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1322:14)
E/flutter (26353): #57     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (26353): #58     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (26353): 
E/flutter (26353): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unimplemented handling of missing static target
E/flutter (26353): #0      EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
E/flutter (26353): #1      List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (26353): #2      EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
E/flutter (26353): #3      Function._apply (dart:core-patch/function_patch.dart:11:73)
E/flutter (26353): #4      Function.apply (dart:core-patch/function_patch.dart:34:12)
E/flutter (26353): #5      Socket.onevent (package:socket_io_client/src/socket.dart:308:18)
E/flutter (26353): #6      Socket.onpacket (package:socket_io_client/src/socket.dart:264:9)
E/flutter (26353): #7      EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
E/flutter (26353): #8      List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (26353): #9      EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
E/flutter (26353): #10     Manager.ondecoded (package:socket_io_client/src/manager.dart:253:5)
E/flutter (26353): #11     EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
E/flutter (26353): #12     List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (26353): #13     EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
E/flutter (26353): #14     Decoder.add (package:socket_io_common/src/parser/parser.dart:160:14)
E/flutter (26353): #15     Manager.ondata (package:socket_io_client/src/manager.dart:244:13)
E/flutter (26353): #16     EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
E/flutter (26353): #17     List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (26353): #18     EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
E/flutter (26353): #19     Socket.onPacket (package:socket_io_client/src/engine/socket.dart:463:11)
E/flutter (26353): #20     Socket.setTransport.<anonymous closure> (package:socket_io_client/src/engine/socket.dart:287:34)
E/flutter (26353): #21     EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
E/flutter (26353): #22     List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (26353): #23     EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
E/flutter (26353): #24     Transport.onPacket (package:socket_io_client/src/engine/transport/transport.dart:127:5)
E/flutter (26353): #25     Transport.onData (package:socket_io_client/src/engine/transport/transport.dart:121:5)
E/flutter (26353): #26     IOWebSocketTransport.addEventListeners.<anonymous closure> (package:socket_io_client/src/engine/transport/io_websocket_transport.dart:67:7)
E/flutter (26353): #27     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (26353): #28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (26353): #29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (26353): #30     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
E/flutter (26353): #31     _StreamController._add (dart:async/stream_controller.dart:648:7)
E/flutter (26353): #32     _StreamController.add (dart:async/stream_controller.dart:596:5)
E/flutter (26353): #33     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1144:21)
E/flutter (26353): #34     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (26353): #35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (26353): #36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (26353): #37     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
E/flutter (26353): #38     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
E/flutter (26353): #39     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:332:23)
E/flutter (26353): #40     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:226:46)
E/flutter (26353): #41     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
E/flutter (26353): #42     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (26353): #43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (26353): #44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (26353): #45     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
E/flutter (26353): #46     _StreamController._add (dart:async/stream_controller.dart:648:7)
E/flutter (26353): #47     _StreamController.add (dart:async/stream_controller.dart:596:5)
E/flutter (26353): #48     _Socket._onData (dart:io-patch/socket_patch.dart:2324:41)
E/flutter (26353): #49     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (26353): #50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (26353): #51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (26353): #52     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
E/flutter (26353): #53     _StreamController._add (dart:async/stream_controller.dart:648:7)
E/flutter (26353): #54     _StreamController.add (dart:async/stream_controller.dart:596:5)
E/flutter (26353): #55     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1849:33)
E/flutter (26353): #56     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1322:14)
E/flutter (26353): #57     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (26353): #58     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (26353): 
E/flutter (26353): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unimplemented handling of missing static target
E/flutter (26353): #0      EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
E/flutter (26353): #1      List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (26353): #2      EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
E/flutter (26353): #3      Function._apply (dart:core-patch/function_patch.dart:11:73)
E/flutter (26353): #4      Function.apply (dart:core-patch/function_patch.dart:34:12)
E/flutter (26353): #5      Socket.onevent (package:socket_io_client/src/socket.dart:308:18)
E/flutter (26353): #6      Socket.onpacket (package:socket_io_client/src/socket.dart:264:9)
E/flutter (26353): #7      EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
E/flutter (26353): #8      List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (26353): #9      EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
E/flutter (26353): #10     Manager.ondecoded (package:socket_io_client/src/manager.dart:253:5)
E/flutter (26353): #11     EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
E/flutter (26353): #12     List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (26353): #13     EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
E/flutter (26353): #14     Decoder.add (package:socket_io_common/src/parser/parser.dart:160:14)
E/flutter (26353): #15     Manager.ondata (package:socket_io_client/src/manager.dart:244:13)
E/flutter (26353): #16     EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
E/flutter (26353): #17     List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (26353): #18     EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
E/flutter (26353): #19     Socket.onPacket (package:socket_io_client/src/engine/socket.dart:463:11)
E/flutter (26353): #20     Socket.setTransport.<anonymous closure> (package:socket_io_client/src/engine/socket.dart:287:34)
E/flutter (26353): #21     EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
E/flutter (26353): #22     List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (26353): #23     EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
E/flutter (26353): #24     Transport.onPacket (package:socket_io_client/src/engine/transport/transport.dart:127:5)
E/flutter (26353): #25     Transport.onData (package:socket_io_client/src/engine/transport/transport.dart:121:5)
E/flutter (26353): #26     IOWebSocketTransport.addEventListeners.<anonymous closure> (package:socket_io_client/src/engine/transport/io_websocket_transport.dart:67:7)
E/flutter (26353): #27     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (26353): #28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (26353): #29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (26353): #30     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
E/flutter (26353): #31     _StreamController._add (dart:async/stream_controller.dart:648:7)
E/flutter (26353): #32     _StreamController.add (dart:async/stream_controller.dart:596:5)
E/flutter (26353): #33     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1144:21)
E/flutter (26353): #34     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (26353): #35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (26353): #36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (26353): #37     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
E/flutter (26353): #38     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
E/flutter (26353): #39     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:332:23)
E/flutter (26353): #40     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:226:46)
E/flutter (26353): #41     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
E/flutter (26353): #42     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (26353): #43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (26353): #44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (26353): #45     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
E/flutter (26353): #46     _StreamController._add (dart:async/stream_controller.dart:648:7)
E/flutter (26353): #47     _StreamController.add (dart:async/stream_controller.dart:596:5)
E/flutter (26353): #48     _Socket._onData (dart:io-patch/socket_patch.dart:2324:41)
E/flutter (26353): #49     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (26353): #50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (26353): #51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (26353): #52     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
E/flutter (26353): #53     _StreamController._add (dart:async/stream_controller.dart:648:7)
E/flutter (26353): #54     _StreamController.add (dart:async/stream_controller.dart:596:5)
E/flutter (26353): #55     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1849:33)
E/flutter (26353): #56     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1322:14)
E/flutter (26353): #57     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (26353): #58     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (26353): 
E/flutter (26353): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unimplemented handling of missing static target
E/flutter (26353): #0      EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
E/flutter (26353): #1      List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (26353): #2      EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
E/flutter (26353): #3      Function._apply (dart:core-patch/function_patch.dart:11:73)
E/flutter (26353): #4      Function.apply (dart:core-patch/function_patch.dart:34:12)
E/flutter (26353): #5      Socket.onevent (package:socket_io_client/src/socket.dart:308:18)
E/flutter (26353): #6      Socket.onpacket (package:socket_io_client/src/socket.dart:264:9)
E/flutter (26353): #7      EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
E/flutter (26353): #8      List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (26353): #9      EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
E/flutter (26353): #10     Manager.ondecoded (package:socket_io_client/src/manager.dart:253:5)
E/flutter (26353): #11     EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
E/flutter (26353): #12     List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (26353): #13     EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
E/flutter (26353): #14     Decoder.add (package:socket_io_common/src/parser/parser.dart:160:14)
E/flutter (26353): #15     Manager.ondata (package:socket_io_client/src/manager.dart:244:13)
E/flutter (26353): #16     EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
E/flutter (26353): #17     List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (26353): #18     EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
E/flutter (26353): #19     Socket.onPacket (package:socket_io_client/src/engine/socket.dart:463:11)
E/flutter (26353): #20     Socket.setTransport.<anonymous closure> (package:socket_io_client/src/engine/socket.dart:287:34)
E/flutter (26353): #21     EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
E/flutter (26353): #22     List.forEach (dart:core-patch/growable_array.dart:416:8)
E/flutter (26353): #23     EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
E/flutter (26353): #24     Transport.onPacket (package:socket_io_client/src/engine/transport/transport.dart:127:5)
E/flutter (26353): #25     Transport.onData (package:socket_io_client/src/engine/transport/transport.dart:121:5)
E/flutter (26353): #26     IOWebSocketTransport.addEventListeners.<anonymous closure> (package:socket_io_client/src/engine/transport/io_websocket_transport.dart:67:7)
E/flutter (26353): #27     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (26353): #28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (26353): #29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (26353): #30     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
E/flutter (26353): #31     _StreamController._add (dart:async/stream_controller.dart:648:7)
E/flutter (26353): #32     _StreamController.add (dart:async/stream_controller.dart:596:5)
E/flutter (26353): #33     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1144:21)
E/flutter (26353): #34     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (26353): #35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (26353): #36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (26353): #37     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
E/flutter (26353): #38     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
E/flutter (26353): #39     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:332:23)
E/flutter (26353): #40     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:226:46)
E/flutter (26353): #41     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
E/flutter (26353): #42     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (26353): #43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (26353): #44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (26353): #45     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
E/flutter (26353): #46     _StreamController._add (dart:async/stream_controller.dart:648:7)
E/flutter (26353): #47     _StreamController.add (dart:async/stream_controller.dart:596:5)
E/flutter (26353): #48     _Socket._onData (dart:io-patch/socket_patch.dart:2324:41)
E/flutter (26353): #49     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (26353): #50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (26353): #51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (26353): #52     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
E/flutter (26353): #53     _StreamController._add (dart:async/stream_controller.dart:648:7)
E/flutter (26353): #54     _StreamController.add (dart:async/stream_controller.dart:596:5)
E/flutter (26353): #55     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1849:33)
E/flutter (26353): #56     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1322:14)
E/flutter (26353): #57     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (26353): #58     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

my ios getter 
```
Socket getSocket() {
    return io(
      ApiConstants.baseServerIp,
      OptionBuilder()
          .setQuery({
            "auth":
                "Bearer ${AppPref.getHashedString(key: StorageKeys.accessToken)}",
          })
          .setExtraHeaders({
            'Authorization':
                "Bearer ${AppPref.getHashedString(key: StorageKeys.accessToken)}",
            "accept-language": "en"
          })
          .setTransports(['websocket'])
          .disableReconnection()
          .disableAutoConnect()
          .build(),
    );
  }
```

**Comment by jumperchen** [comment]
Have you tried a hot restart?

**Comment by hatemragab** [comment]
Yes it works after hot restart
