### ISSUE TITLE
Unhandled Exception: RangeError (index): Invalid value: Not in inclusive range 0..7: 8

### ISSUE THREAD

**Issue by silasrm** [rikulo/socket.io-client-dart#323]
Hi guys,

I'm trying to connect to a exists websocket:

```
// WS_URL=wss://ws....

socket = IO.io(
          '${dotenv.env["WS_URL"].toString()}:443/painel',
          IO.OptionBuilder()
            .setQuery(<String, dynamic>{
              'token': token,
              // 'transports': ['websocket'],
              // 'autoConnect': true,
            })
            .enableAutoConnect()
            .setTransports(['websocket'])
            .build()
      );
```

And this error occurs:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (index): Invalid value: Not in inclusive range 0..7: 8
#0      _StringBase.[] (dart:core-patch/string_patch.dart:258:41)
#1      Decoder.decodeString (package:socket_io_common/src/parser/parser.dart:213:20)
#2      Decoder.add (package:socket_io_common/src/parser/parser.dart:149:16)
#3      Manager.ondata (package:socket_io_client/src/manager.dart:244:13)
#4      EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
#5      List.forEach (dart:core-patch/growable_array.dart:416:8)
#6      EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
#7      Socket.onPacket (package:socket_io_client/src/engine/socket.dart:463:11)
#8      Socket.setTransport.<anonymous closure> (package:socket_io_client/src/engine/socket.dart:287:34)
#9      EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
#10     List.forEach (dart:core-patch/growable_array.dart:416:8)
#11     EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
#12     Transport.onPacket (package:socket_io_client/src/engine/transport/transport.dart:127:5)
#13     Transport.onData (package:socket_io_client/src/engine/transport/transport.dart:121:5)
#14     IOWebSocketTransport.addEventListeners.<anonymous closure> (package:socket_io_client/src/engine/transport/io_websocket_transport.dart:67:7)
#15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#18     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#19     _StreamController._add (dart:async/stream_controller.dart:648:7)
#20     _StreamController.add (dart:async/stream_controller.dart:596:5)
#21     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1144:21)
#22     _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#25     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#26     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#27     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:332:23)
#28     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:226:46)
#29     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#30     _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#33     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#34     _StreamController._add (dart:async/stream_controller.dart:648:7)
#35     _StreamController.add (dart:async/stream_controller.dart:596:5)
#36     _Socket._onData (dart:io-patch/socket_patch.dart:2355:41)
#37     _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#41     _StreamController._add (dart:async/stream_controller.dart:648:7)
#42     _StreamController.add (dart:async/stream_controller.dart:596:5)
#43     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1111:19)
#44     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#45     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#46     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#47     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```
Any idea how to debug?

Lib: socket_io_client: ^2.0.1
Flutter: 3.7.5

Thanks

**Comment by silasrm** [comment]
My fix: https://github.com/rikulo/socket_io_common/pull/9

**Comment by silasrm** [comment]
Hi guys,

I'm upgrade my websocket to v3 and know everything is running ok :D
