### ISSUE TITLE
Empty query map in OptionsBuilder throws RangeError

### ISSUE THREAD

**Issue by jaween** [rikulo/socket.io-client-dart#343]
When constructing a client with an empty query, an error is thrown.

Code sample:
```dart
final client = io(
      'http://example.com',
      OptionBuilder()
          .setTimeout(1500)
          .setTransports(['websocket'])
          .setQuery({})
          .enableForceNew()
          .build(),
    );
```
Notice that the query is set to `{}` (this happens for me when I have a conditional entry in the map).

The error that is thrown is:
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (index): Invalid value: Only valid value is 0: 1
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      decode
parseqs.dart:35
#2      new Socket
socket.dart:100
#3      Manager.connect
manager.dart:147
#4      Manager.open
manager.dart:140
#5      Manager.reconnect.<anonymous closure>
manager.dart:411
#6      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

**Comment by marcusgregory** [comment]
The same problem happens to me in the latest stable version, even if I don't explicitly pass setQuery({})

**Comment by jumperchen** [comment]
@marcusgregory please use [v3.0.0-beta.2](https://github.com/rikulo/socket.io-client-dart/releases/tag/v3.0.0-beta.2)

**Comment by marcusgregory** [comment]
I managed to use this stable version, I simply used setQuery({'',''}) and it worked, maybe in future versions, check if the map is null or empty before doing split operations
