### ISSUE TITLE
Unhandled Exception: Unsupported operation: invalid payload

### ISSUE THREAD

**Issue by dghub-founder** [rikulo/socket.io-client-dart#348]

**Comment by jumperchen** [comment]
any error logs?

**Comment by TheAlphamerc** [comment]
Getting the same error on getting the data for subscribed events.
## Logs:
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Unsupported operation: invalid payload
#0      Decoder.decodeString (package:socket_io_common/src/parser/parser.dart:243:9)
#1      Decoder.add (package:socket_io_common/src/parser/parser.dart:149:16)
#2      Manager.ondata (package:socket_io_client/src/manager.dart:246:13)
#3      EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
#4      List.forEach (dart:core-patch/growable_array.dart:416:8)
#5      EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
#6      Socket.onPacket (package:socket_io_client/src/engine/socket.dart:462:11)
#7      Socket.setTransport.<anonymous closure> (package:socket_io_client/src/engine/socket.dart:286:34)
#8      EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
#9      List.forEach (dart:core-patch/growable_array.dart:416:8)
#10     EventEmitter.emit (package:socket_io_common/src/util/ev<…>
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Unsupported operation: invalid payload
#0      Decoder.decodeString (package:socket_io_common/src/parser/parser.dart:243:9)
#1      Decoder.add (package:socket_io_common/src/parser/parser.dart:149:16)
#2      Manager.ondata (package:socket_io_client/src/manager.dart:246:13)
#3      EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
#4      List.forEach (dart:core-patch/growable_array.dart:416:8)
#5      EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
#6      Socket.onPacket (package:socket_io_client/src/engine/socket.dart:462:11)
#7      Socket.setTransport.<anonymous closure> (package:socket_io_client/src/engine/socket.dart:286:34)
#8      EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
#9      List.forEach (dart:core-patch/growable_array.dart:416:8)
#10     EventEmitter.emit (package:socket_io_common/src/util/ev<…>
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Unsupported operation: invalid payload
#0      Decoder.decodeString (package:socket_io_common/src/parser/parser.dart:243:9)
#1      Decoder.add (package:socket_io_common/src/parser/parser.dart:149:16)
#2      Manager.ondata (package:socket_io_client/src/manager.dart:246:13)
#3      EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
#4      List.forEach (dart:core-patch/growable_array.dart:416:8)
#5      EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
#6      Socket.onPacket (package:socket_io_client/src/engine/socket.dart:462:11)
#7      Socket.setTransport.<anonymous closure> (package:socket_io_client/src/engine/socket.dart:286:34)
#8      EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
#9      List.forEach (dart:core-patch/growable_array.dart:416:8)
#10     EventEmitter.emit (package:socket_io_common/src/util/ev<…>
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Unsupported operation: invalid payload
#0      Decoder.decodeString (package:socket_io_common/src/parser/parser.dart:243:9)
#1      Decoder.add (package:socket_io_common/src/parser/parser.dart:149:16)
#2      Manager.ondata (package:socket_io_client/src/manager.dart:246:13)
#3      EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
#4      List.forEach (dart:core-patch/growable_array.dart:416:8)
#5      EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
#6      Socket.onPacket (package:socket_io_client/src/engine/socket.dart:462:11)
#7      Socket.setTransport.<anonymous closure> (package:socket_io_client/src/engine/socket.dart:286:34)
#8      EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
#9      List.forEach (dart:core-patch/growable_array.dart:416:8)
#10     EventEmitter.emit (package:socket_io_common/src/util/ev<…>
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Unsupported operation: invalid payload
#0      Decoder.decodeString (package:socket_io_common/src/parser/parser.dart:243:9)
#1      Decoder.add (package:socket_io_common/src/parser/parser.dart:149:16)
#2      Manager.ondata (package:socket_io_client/src/manager.dart:246:13)
#3      EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
#4      List.forEach (dart:core-patch/growable_array.dart:416:8)
#5      EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
#6      Socket.onPacket (package:socket_io_client/src/engine/socket.dart:462:11)
#7      Socket.setTransport.<anonymous closure> (package:socket_io_client/src/engine/socket.dart:286:34)
#8      EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
#9      List.forEach (dart:core-patch/growable_array.dart:416:8)
#10     EventEmitter.emit (package:socket_io_common/src/util/ev<…>
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Unsupported operation: invalid payload
#0      Decoder.decodeString (package:socket_io_common/src/parser/parser.dart:243:9)
#1      Decoder.add (package:socket_io_common/src/parser/parser.dart:149:16)
#2      Manager.ondata (package:socket_io_client/src/manager.dart:246:13)
#3      EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
#4      List.forEach (dart:core-patch/growable_array.dart:416:8)
#5      EventEmitter.emit (package:socket_io_common/src/util/event_emitter.dart:60:11)
#6      Socket.onPacket (package:socket_io_client/src/engine/socket.dart:462:11)
#7      Socket.setTransport.<anonymous closure> (package:socket_io_client/src/engine/socket.dart:286:34)
#8      EventEmitter.emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:61:14)
#9      List.forEach (dart:core-patch/growable_array.dart:416:8)
#10     EventEmitter.emit (package:socket_io_common/src/util/ev<…>

```

**Comment by jumperchen** [comment]
@TheAlphamerc Could you please provide the version information for both the server and the client?

**Comment by TheAlphamerc** [comment]
## Flutter
[socket_io_client: ^2.0.3+1](https://pub.dev/packages/socket_io_client/versions/2.0.3+1)

## Node
[socket.io@3.1.2](https://www.npmjs.com/package/socket.io/v/3.1.2)

**Comment by TheAlphamerc** [comment]
@jumperchen It seems like the server is sending invalid JSON data. So I think the issue is not related to the socket client package itself.
<img width="1565" alt="Screenshot 2024-01-14 at 6 21 11 PM" src="https://github.com/rikulo/socket.io-client-dart/assets/37103237/a42c8680-a4c7-4438-88ee-df54d07aa494">

**Comment by maheshmesta** [comment]
Hi. even i am facing the same issue in flutter windows  
``` yaml
socket_io_client: ^2.0.1
```
