### ISSUE TITLE
type 'String' is not a subtype of type 'int' of 'index'

### ISSUE THREAD

**Issue by ChiJohn** [rikulo/socket.io-client-dart#387]
The following _TypeError was thrown:
type 'String' is not a subtype of type 'int' of 'index'

When the exception was thrown, this was the stack:
#0      Socket.onpacket (package:socket_io_client/src/socket.dart:398:53)
#1      EventEmitter._emit.<anonymous closure> (package:socket_io_common/src/util/event_emitter.dart:44:14)
#2      List.forEach (dart:core-patch/growable_array.dart:416:8)
#3      EventEmitter._emit (package:socket_io_common/src/util/event_emitter.dart:43:11)
#4      EventEmitter.emitReserved (package:socket_io_common/src/util/event_emitter.dart:57:47)
#5      Manager.ondecoded.<anonymous closure> (package:socket_io_client/src/manager.dart:276:7)
(elided 11 frames from dart:async)

**Comment by ChiJohn** [comment]
pubspec.yaml
    socket_io_client: ^3.0.0-beta.1
 
flutter doctor
 
![image](https://github.com/user-attachments/assets/5892b703-6ebd-47d3-afa3-e6aaec6125e5)

**Comment by jumperchen** [comment]
any reproducible example? or please test with the latest 3.0.0-beta.4 version to give it a try.

**Comment by bbright-dinesh** [comment]
I have the same issue, but it's not the problem with this client.

If we have incompatible socket server version (1.7.0 in my case), and client version is (3.0.2), then we are getting the same error.
After changing the server to be compatible with client version (both server, client are same), then the problem is solved.
