### ISSUE TITLE
WebSocketException: Connection to was not upgraded to websocket

### ISSUE THREAD

**Issue by pnkmem429** [rikulo/socket.io-client-dart#401]
```
E/flutter (15940): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: WebSocketException: Connection to 'http://abcd.com:0/ws/#' was not upgraded to websocket
E/flutter (15940): #0      _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1011:41)
E/flutter (15940): #1      WebSocket.connect (dart:_http/websocket.dart:320:22)
E/flutter (15940): #2      new IOWebSocketChannel.connect (package:web_socket_channel/io.dart:81:28)
E/flutter (15940): #3      connect (package:web_socket_channel/src/_connect_io.dart:15:24)
E/flutter (15940): #4      new WebSocketChannel.connect (package:web_socket_channel/src/channel.dart:115:16)
E/flutter (15940): #5      new WebSocketProvider (package:m2_ua/data/provider/base/data_provider.dart:15:33)
E/flutter (15940): #6      new RecordPerformProvider (package:m2_ua/data/provider/record_perform_provider.dart)
E/flutter (15940): #7      RecordPerformRepository.insertSet (package:m2_ua/data/repository/record_perform_repository.dart:51:20)
E/flutter (15940): #8      HMIController.savePerformSet (package:m2_ua/feature/hmi/main/hmi_view_model.dart:621:49)
E/flutter (15940): #9      HMIController.savePerform (package:m2_ua/feature/hmi/main/hmi_view_model.dart:535:11)
E/flutter (15940): <asynchronous suspension>
E/flutter (15940): 
I/flutter (15940):     ------------------------[WebSocket: onError]----------------------------
I/flutter (15940):     WebSocketChannelException: WebSocketChannelException: WebSocketException: Connection to 'http://abcd.com:0/ws/#' was not upgraded to websocket
I/flutter (15940):     

```

I was using well until last Friday, but today, suddenly these error logs come out everywhere.

**Comment by jumperchen** [comment]
We didn't change this library recently. Any other information for us to identify this issue?

**Comment by yajatkaul** [comment]
i have the same issue some say it is because of different server and client socket versions some just ask me to add 
```<application android:usesCleartextTraffic="true"/>```
but nothing works kindly look into it

my express server is using socket.io v^4.8.1 and my flutter app is using v^3.0.2

**Comment by yajatkaul** [comment]
Okay i checked again found it to be a server side issue plugin seems to be fine

**Comment by KushUmenit** [comment]
I am still facing an issue with socket.io version ^3.0.2. Please help us resolve this on the Flutter side, as we are using version 4.8.1 version on node side. I believe they are not compatible with each other. Could you provide assistance with this?

![Image](https://github.com/user-attachments/assets/7917326b-7690-4388-aff5-dc9bef43078e)

**Comment by bqubique** [comment]
> Okay i checked again found it to be a server side issue plugin seems to be fine

same for me, when I try via `wscat` the same issue seems to happen.
